Repository webp-sh/webp_server_go, pull requests merged in 2020-03, with the labels that each got.

#13 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#16 Added custom exhaust path.
  README.md
  config.json
  scripts/webp_server.spec
  webp-server.go
Labels: in review

#18 Add features
  README.md
  config.json
  go.mod
  pics/no.gif
  pics/webp_server.bmp
  webp-server.go
Labels: enhancement

#19 auto update in background
  README.md
  webp-server.go
Labels: enhancement
